apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: mc-pv-1