apiVersion: v1
kind: Service
metadata:
  name: mc-service-1
spec:
  type: NodePort
  selector:
    app: mc-server-1
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30001